CREATE PROCEDURE SP_InsereBeneficiario
    @CPF VARCHAR(14),
    @NOME VARCHAR(100),
    @IDCLIENTE INT
AS
BEGIN
    INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE)
    VALUES (@CPF, @NOME, @IDCLIENTE);
END